name: Frontend Checks
description:
  "Runs all of the common checks for a frontend application on the specified package: TypeScript,
  ESLint, and Prettier. The package must be a package the pnpm knows about from
  `pnpm-workspace.yaml. Multiple packages can also be specified using pnpm's filter syntax (without
  quotes)"
inputs:
  package:
    required: true
    type: string
    description: Package filter to use for running the checks.

runs:
  using: composite
  steps:
    - name: "ESLint"
      shell: bash
      run: pnpm --filter ${{inputs.package}} -r lint

    - name: "Prettier"
      shell: bash
      run: pnpm --filter ${{inputs.package}} -r prettier

    - name: "TypeScript"
      shell: bash
      run: pnpm --filter ${{inputs.package}} -r tsc
