name: Spyrothon Admin

on:
  push:
    branches: [main]
    paths:
      - "packages/admin/**"
      - "packages/api/**"
      - "packages/uikit/**"
      - "vendored/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./packages/admin
          needs_vendored_dependencies: true

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-on-render.yaml
    with:
      service_name: admin
    secrets:
      deploy_hook: ${{ secrets.ADMIN_DEPLOY_HOOK }}
