name: Spyrothon Admin

on:
  push:
    branches: [main]
    paths:
      - "packages/admin/**"
      - "packages/api/**"
      - "packages/uikit/**"
      - "vendored/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./packages/admin
          needs_vendored_dependencies: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render.com
        uses: techeca/render-deployHook-action@0.1.0
        with:
          deploy-hook: ${{ secrets.ADMIN_DEPLOY_HOOK }}
