name: Spyrothon App

on:
  push:
    branches: [main]
    paths:
      - "packages/app/**"
      - "packages/api/**"
      - "packages/uikit/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./packages/app
          needs_vendored_dependencies: false

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-on-render.yaml
    with:
      deploy_hook: ${{ secrets.APP_DEPLOY_HOOK }}
