deploname: Deploy on Render.com

on:
  workflow_call:
    inputs:
      deploy_hook:
        required: true
        type: string
      service_name:
        require: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy `${{ inputs.service_name }}` to Render.com
        uses: ungnome/render-service-deploy@6cae7802c0367cfb0fa7848e18745ba675b35aef
        with:
          webhook: ${{ inputs.deploy_hook }}
          api-key: ${{ secrets.RENDER_API_KEY }}
