name: Deploy on Render.com

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      deploy_hook:
        required: true

concurrency:
  group: ${{ github.ref }}-${{ inputs.service_name }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Production
    if: github.ref == 'main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render.com
        uses: techeca/render-deployHook-action@0.1.0
        with:
          deploy-hook: ${{ secrets.deploy_hook }}
