name: Spyrothon Graphics

on:
  push:
    branches: [main]
    paths:
      - "packages/graphics/**"
      - "packages/api/**"
      - "packages/uikit/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./packages/graphics
          needs_vendored_dependencies: false

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render.com
        uses: techeca/render-deployHook-action@0.1.0
        with:
          deploy-hook: ${{ secrets.GRAPHICS_DEPLOY_HOOK }}
