name: Spyrothon Graphics

on:
  push:
    branches: [main]
    paths:
      - "packages/graphics/**"
      - "packages/api/**"
      - "packages/uikit/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./packages/graphics
          needs_vendored_dependencies: false

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-on-render.yaml
    with:
      service_name: graphics
    secrets:
      deploy_hook: ${{ secrets.GRAPHICS_DEPLOY_HOOK }}
