name: Spyrothon Graphics

on:
  push:
    branches: [main]
    paths:
      - "spyrothon_graphics/**"
      - "packages/api/**"
      - "packages/utils/**"
  pull_request:
    paths:
      - "spyrothon_graphics/**"
      - "packages/api/**"
      - "packages/utils/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        uses: ./.github/actions/prereqs

      - name: Frontend Checks
        uses: ./.github/actions/frontend-checks
        with:
          package: ./spyrothon_graphics
